"""
Treasury Portfolio Financial Data.

AUTO-GENERATED by tools/sync_excel.py — DO NOT EDIT MANUALLY.
Last synced: 2026-06-15 16:24:39
Source: Mapping WC-Invest 26.04.xlsx
"""

FINANCIAL_DATA = {
    "summary": {
        "totalLoan": 1219358926154.0,
        "totalInvest": 1481603094800.0,
        "fundingRate": 6.98,
        "investYield": 8.84,
        "netSpread": 1.86,
        "netPL": 43593948337.391396,
        "tdPct": 25.6,
        "bondPct": 74.4,
        "tdAmount": 380000000000.0,
        "bondAmount": 1101603094800.0,
        "totalTSDB": 240500000000.0,
        "totalHanMuc": 1610000000000.0
    },
    "limitControls": [
        {
            "bank": "VCB",
            "duNo": 653901174143.0,
            "hanMuc": 750000000000.0,
            "util": 87.2,
            "room": 96098825857.0,
            "status": "warning"
        },
        {
            "bank": "BIDV",
            "duNo": 94536165147.0,
            "hanMuc": 250000000000.0,
            "util": 37.8,
            "room": 155463834853.0,
            "status": "safe"
        },
        {
            "bank": "Cathay",
            "duNo": 200000000000.0,
            "hanMuc": 200000000000.0,
            "util": 100.0,
            "room": 0.0,
            "status": "danger"
        },
        {
            "bank": "Shinhan",
            "duNo": 159921586864.0,
            "hanMuc": 160000000000.0,
            "util": 100.0,
            "room": 78413136.0,
            "status": "danger"
        },
        {
            "bank": "HSBC",
            "duNo": 111000000000.0,
            "hanMuc": 250000000000.0,
            "util": 44.4,
            "room": 139000000000.0,
            "status": "safe"
        }
    ],
    "loans": [
        {
            "bank": "VCB",
            "amount": 74100000000.0,
            "rate": 6.0,
            "startDate": "2025-12-22",
            "endDate": "2026-06-19",
            "status": "Outstanding"
        },
        {
            "bank": "VCB",
            "amount": 119000000000.0,
            "rate": 6.0,
            "startDate": "2026-01-05",
            "endDate": "2026-07-03",
            "status": "Outstanding"
        },
        {
            "bank": "VCB",
            "amount": 87701174143.0,
            "rate": 6.0,
            "startDate": "2026-01-15",
            "endDate": "2026-07-13",
            "status": "Outstanding"
        },
        {
            "bank": "VCB",
            "amount": 72100000000.0,
            "rate": 6.0,
            "startDate": "2026-01-20",
            "endDate": "2026-07-20",
            "status": "Outstanding"
        },
        {
            "bank": "Cathay",
            "amount": 200000000000.0,
            "rate": 7.2,
            "startDate": "2026-02-05",
            "endDate": "2026-08-04",
            "status": "Outstanding"
        },
        {
            "bank": "Shinhan",
            "amount": 143663435630.0,
            "rate": 6.9,
            "startDate": "2026-04-15",
            "endDate": "2026-10-15",
            "status": "Outstanding"
        },
        {
            "bank": "Shinhan",
            "amount": 9637371651.0,
            "rate": 6.9,
            "startDate": "2026-04-20",
            "endDate": "2026-10-20",
            "status": "Outstanding"
        },
        {
            "bank": "Shinhan",
            "amount": 6620779583.0,
            "rate": 6.9,
            "startDate": "2026-04-23",
            "endDate": "2026-10-23",
            "status": "Outstanding"
        },
        {
            "bank": "VCB",
            "amount": 124000000000.0,
            "rate": 8.0,
            "startDate": "2026-04-20",
            "endDate": "2026-10-19",
            "status": "Outstanding"
        },
        {
            "bank": "VCB",
            "amount": 177000000000.0,
            "rate": 8.0,
            "startDate": "2026-05-05",
            "endDate": "2026-11-02",
            "status": "Outstanding"
        },
        {
            "bank": "BIDV",
            "amount": 14709047762.0,
            "rate": 7.0,
            "startDate": "2026-05-05",
            "endDate": "2026-11-02",
            "status": "Outstanding"
        },
        {
            "bank": "BIDV",
            "amount": 79827117385.0,
            "rate": 7.0,
            "startDate": "2026-05-11",
            "endDate": "2026-11-06",
            "status": "Outstanding"
        },
        {
            "bank": "HSBC",
            "amount": 111000000000.0,
            "rate": 7.0,
            "startDate": "2026-06-05",
            "endDate": "2026-11-02",
            "status": "Outstanding"
        }
    ],
    "investments": [
        {
            "bank": "TCBS",
            "amount": 221128300000.0,
            "rate": 8.0,
            "type": "BOND",
            "startDate": "2025-12-16",
            "endDate": "2026-06-16",
            "status": "Outstanding"
        },
        {
            "bank": "TCBS",
            "amount": 120736438800.0,
            "rate": 8.5,
            "type": "BOND",
            "startDate": "2026-01-28",
            "endDate": "2026-07-28",
            "status": "Outstanding"
        },
        {
            "bank": "VPB",
            "amount": 100000000000.0,
            "rate": 8.3,
            "type": "TD",
            "startDate": "2026-01-28",
            "endDate": "2026-07-28",
            "status": "Outstanding"
        },
        {
            "bank": "VPB",
            "amount": 70000000000.0,
            "rate": 8.3,
            "type": "TD",
            "startDate": "2026-01-28",
            "endDate": "2026-07-28",
            "status": "Outstanding"
        },
        {
            "bank": "VHM",
            "amount": 207457534000.0,
            "rate": 9.0,
            "type": "BOND",
            "startDate": "2026-02-06",
            "endDate": "2026-08-06",
            "status": "Outstanding"
        },
        {
            "bank": "TVS",
            "amount": 150000000000.0,
            "rate": 9.0,
            "type": "BOND",
            "startDate": "2026-03-16",
            "endDate": "2026-06-16",
            "status": "Outstanding"
        },
        {
            "bank": "TVS",
            "amount": 152280822000.0,
            "rate": 9.3,
            "type": "BOND",
            "startDate": "2026-05-28",
            "endDate": "2026-11-30",
            "status": "Outstanding"
        },
        {
            "bank": "TCBS",
            "amount": 250000000000.0,
            "rate": 9.2,
            "type": "BOND",
            "startDate": "2026-06-02",
            "endDate": "2026-12-02",
            "status": "Outstanding"
        },
        {
            "bank": "VPB",
            "amount": 210000000000.0,
            "rate": 9.3,
            "type": "TD",
            "startDate": "2026-06-12",
            "endDate": "2026-12-12",
            "status": "Outstanding"
        }
    ],
    "durationMismatches": [
        {
            "investBank": "TVS",
            "loanBank": "Shinhan",
            "investEnd": "2026-06-16",
            "loanEnd": "2026-10-20",
            "daysDiff": 126,
            "investAmt": 150000000000.0,
            "loanAmt": 9637371651.0
        },
        {
            "investBank": "TCBS",
            "loanBank": "VCB",
            "investEnd": "2026-12-02",
            "loanEnd": "2026-10-19",
            "daysDiff": 44,
            "investAmt": 250000000000.0,
            "loanAmt": 124000000000.0
        },
        {
            "investBank": "VPB",
            "loanBank": "BIDV",
            "investEnd": "2026-12-12",
            "loanEnd": "2026-11-02",
            "daysDiff": 40,
            "investAmt": 210000000000.0,
            "loanAmt": 14709047762.0
        },
        {
            "investBank": "TVS",
            "loanBank": "Shinhan",
            "investEnd": "2026-11-30",
            "loanEnd": "2026-10-23",
            "daysDiff": 38,
            "investAmt": 152280822000.0,
            "loanAmt": 6620779583.0
        },
        {
            "investBank": "TCBS",
            "loanBank": "VCB",
            "investEnd": "2026-07-28",
            "loanEnd": "2026-07-03",
            "daysDiff": 25,
            "investAmt": 120736438800.0,
            "loanAmt": 119000000000.0
        },
        {
            "investBank": "VPB",
            "loanBank": "VCB",
            "investEnd": "2026-07-28",
            "loanEnd": "2026-07-13",
            "daysDiff": 15,
            "investAmt": 100000000000.0,
            "loanAmt": 87701174143.0
        },
        {
            "investBank": "VPB",
            "loanBank": "VCB",
            "investEnd": "2026-07-28",
            "loanEnd": "2026-07-20",
            "daysDiff": 8,
            "investAmt": 70000000000.0,
            "loanAmt": 72100000000.0
        },
        {
            "investBank": "VHM",
            "loanBank": "Cathay",
            "investEnd": "2026-08-06",
            "loanEnd": "2026-08-04",
            "daysDiff": 2,
            "investAmt": 207457534000.0,
            "loanAmt": 200000000000.0
        }
    ],
    "loanByBank": [
        {
            "bank": "VCB",
            "total": 653901174143.0,
            "count": 6,
            "avgRate": 6.92
        },
        {
            "bank": "Cathay",
            "total": 200000000000.0,
            "count": 1,
            "avgRate": 7.2
        },
        {
            "bank": "Shinhan",
            "total": 159921586864.0,
            "count": 3,
            "avgRate": 6.9
        },
        {
            "bank": "BIDV",
            "total": 94536165147.0,
            "count": 2,
            "avgRate": 7.0
        },
        {
            "bank": "HSBC",
            "total": 111000000000.0,
            "count": 1,
            "avgRate": 7.0
        }
    ],
    "investByBank": [
        {
            "bank": "TCBS",
            "total": 591864738800.0,
            "count": 3,
            "avgRate": 8.61
        },
        {
            "bank": "VPB",
            "total": 380000000000.0,
            "count": 3,
            "avgRate": 8.85
        },
        {
            "bank": "VHM",
            "total": 207457534000.0,
            "count": 1,
            "avgRate": 9.0
        },
        {
            "bank": "TVS",
            "total": 302280822000.0,
            "count": 2,
            "avgRate": 9.15
        }
    ]
}
